# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Oyewale
tagline:          'Code Ninja'
description:      'For the love of Software'
url:              http://wale.oyediran.me

author:
  name:           'Oyewale Oyediran'
  url:            https://twitter.com/waleoyediran

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/waleoyediran/waleoyediran.github.io/

footer-links:
  github:         waleoyediran
  facebook:       waleoyediran 	
  twitter:        waleoyediran
  gplus:          OyewaleOyediran
  linkedin:		  waleoyediran