# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Oyewale
tagline:          'Ill just write what I love'
description:      'No description'
url:              http://waleoyediran.github.io

author:
  name:           'Oyewale Oyediran'
  url:            https://twitter.com/waleoyediran

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/waleoyediran/hyde